#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

FORCE_BUILD=false
TORQUEBOX_VERSION=LATEST
IMMUTANT_VERSION=LATEST

source $OPENSHIFT_REPO_DIR/.openshift/torquebox.sh
source $OPENSHIFT_REPO_DIR/.openshift/immutant.sh
source $OPENSHIFT_REPO_DIR/.openshift/polyglot.sh

download_torquebox
download_immutant
overlay_jboss

bundle_install
#db_migrate

# Insert the TorqueBox and Immutant modules before the jbossas-7 ones
export JBOSS_MODULEPATH_ADD=$OPENSHIFT_DATA_DIR/polyglot/jboss/modules

